function CalculationHeatTransferS1 = import_xslx(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  CALCULATIONHEATTRANSFERS1 = IMPORTFILE1(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  CALCULATIONHEATTRANSFERS1 = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  CALCULATIONHEATTRANSFERS1 = IMPORTFILE1(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CalculationHeatTransferS1 = importfile1("C:\Users\sengu\Documents\Master_Thesis\masterarbeit_V2\Versuchsauswertung\Calculation_Heat_Transfer.xlsx", "3bar", [7, 18]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Jul-2023 14:44:55

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [7, 18];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Rotationspeed", "HeatTransfer", "WaterFlow", "LayerThickness", "PCMState"];
opts.VariableTypes = ["double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, "PCMState", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Rotationspeed", "HeatTransfer", "WaterFlow", "LayerThickness"], "TreatAsMissing", '');

% Import the data
CalculationHeatTransferS1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    CalculationHeatTransferS1 = [CalculationHeatTransferS1; tb]; %#ok<AGROW>
end

end