function DSC_Data = importDSC(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXPALL20230703NANO3KNO3ALASSIIHANKE100300 = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  EXPALL20230703NANO3KNO3ALASSIIHANKE100300 = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ExpAll20230703NaNO3KNO3ALassIIHanke100300 = importfile("C:\Users\sengu\Documents\Master_Thesis\masterarbeit\Versuchsauswertung\DSC_Analysis\ExpAll_2023-07-03_NaNO3KNO3_ALassII_Hanke_100-300°.csv", [42, 57792]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Jul-2023 12:52:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [42, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["TempC", "Timemin", "DSCmWmg", "GasFlowpurge2mlmin", "GasFlowprotectivemlmin", "SensituVmW", "Segment"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
% opts = setvaropts(opts, "DSCmWmg", "WhitespaceRule", "preserve");
% opts = setvaropts(opts, "DSCmWmg", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["TempC", "Timemin", "DSCmWmg", "GasFlowpurge2mlmin", "GasFlowprotectivemlmin", "SensituVmW"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["TempC", "Timemin", "DSCmWmg", "GasFlowpurge2mlmin", "GasFlowprotectivemlmin", "SensituVmW"], "ThousandsSeparator", ".");

% Import the data
DSC_Data = readtable(filename, opts);

end